# Generated by Django 3.2.9 on 2021-11-25 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start_date_time', models.DateTimeField()),
                ('end_date_time', models.DateTimeField(blank=True)),
                ('created_date_time', models.DateTimeField(auto_now_add=True)),
                ('all_day', models.BooleanField()),
                ('location', models.CharField(blank=True, max_length=200)),
                ('description', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
